### PR TITLE
add null check for context

### PR DESCRIPTION
**Pull request by Apisov**
https://github.com/eggheadgames/android-in-app-payments/issues/5

### CODE REVIEW

**Comment by AlexDibrivnyy** [comment]
Code is clear, `readyForUse`is good solutions for IAPHelper. As far I understood, you put `readyForUse` everywhere where context is used. Right?

**Comment by AlexDibrivnyy** [comment]
@Apisov  did you tested it on real device?

**Comment by Apisov** [comment]
@AlexDibrivnyy No, I didn't do this. It was quick fix after Mike noticed a problem, but we decided do not merge it yet.

**Comment by AlexDibrivnyy** [comment]
@Apisov clear, then I will reassign it to Mike.

**Comment by mikemee** [comment]
Thanks @Apisov. Looks like some good preventative checks and a clean solution.

**Pull request merged**
